-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 22:30:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tictactoe` ;

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tictactoe` DEFAULT CHARACTER SET utf8mb3 ;
USE `tictactoe` ;

-- -----------------------------------------------------
-- Table `tictactoe`.`game_setup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`game_setup` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`game_setup` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `player1_char` CHAR(1) NOT NULL DEFAULT 'X',
                                                        `player2_char` CHAR(1) NOT NULL DEFAULT 'O',
                                                        `empty_char` CHAR(1) NOT NULL DEFAULT '_',
                                                        `dimension` BIGINT NOT NULL DEFAULT '3',
                                                        PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `tictactoe`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`player` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`player` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `username` VARCHAR(64) NOT NULL,
                                                    `email` VARCHAR(255) NULL DEFAULT NULL,
                                                    `password` VARCHAR(64) NOT NULL,
                                                    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 4
    DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `email_UNIQUE` ON `tictactoe`.`player` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tictactoe`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`game` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`game` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `player1` INT NOT NULL,
                                                  `player2` INT NOT NULL DEFAULT '1',
                                                  `game_setup_id` INT NOT NULL DEFAULT '1',
                                                  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  `game_status` TINYINT NOT NULL DEFAULT '0' COMMENT '0 - not done (false)\\n1 - done (true)',
                                                  `state` VARCHAR(255) NULL DEFAULT NULL,
                                                  `who_won` INT NULL DEFAULT NULL COMMENT '0 - draw\\n1 - player 1\\n2 - player 2',
                                                  PRIMARY KEY (`id`),
                                                  CONSTRAINT `fk_game_game_setup1`
                                                      FOREIGN KEY (`game_setup_id`)
                                                          REFERENCES `tictactoe`.`game_setup` (`id`),
                                                  CONSTRAINT `fk_player1`
                                                      FOREIGN KEY (`player1`)
                                                          REFERENCES `tictactoe`.`player` (`id`),
                                                  CONSTRAINT `fk_player2`
                                                      FOREIGN KEY (`player2`)
                                                          REFERENCES `tictactoe`.`player` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 6
    DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `player1_UNIQUE` ON `tictactoe`.`game` (`player1` ASC) VISIBLE;

CREATE INDEX `fk_player1_idx` ON `tictactoe`.`game` (`player1` ASC) INVISIBLE;

CREATE INDEX `fk_player2_idx` ON `tictactoe`.`game` (`player2` ASC) VISIBLE;

CREATE INDEX `fk_game_game_setup1_idx` ON `tictactoe`.`game` (`game_setup_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tictactoe`.`move`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`move` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`move` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `game_id` INT NOT NULL,
                                                  `player_id` INT NOT NULL,
                                                  `board_row` BIGINT NOT NULL DEFAULT '3',
                                                  `board_column` BIGINT NOT NULL DEFAULT '3',
                                                  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  PRIMARY KEY (`id`),
                                                  CONSTRAINT `fk_move_game1`
                                                      FOREIGN KEY (`game_id`)
                                                          REFERENCES `tictactoe`.`game` (`id`),
                                                  CONSTRAINT `fk_move_player1`
                                                      FOREIGN KEY (`player_id`)
                                                          REFERENCES `tictactoe`.`player` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `created_UNIQUE` ON `tictactoe`.`move` (`created` ASC) VISIBLE;

CREATE INDEX `fk_move_game1_idx` ON `tictactoe`.`move` (`game_id` ASC) VISIBLE;

CREATE INDEX `fk_move_player1_idx` ON `tictactoe`.`move` (`player_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
