-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 21:35:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tictactoe` ;

-- -----------------------------------------------------
-- Schema tictactoe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tictactoe` DEFAULT CHARACTER SET utf8 ;
USE `tictactoe` ;

-- -----------------------------------------------------
-- Table `tictactoe`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`player` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`player` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `username` VARCHAR(64) NOT NULL,
                                                    `email` VARCHAR(255) NULL,
                                                    `password` VARCHAR(64) NOT NULL,
                                                    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                    `is_bot` TINYINT NOT NULL DEFAULT 0,
                                                    PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `email_UNIQUE` ON `tictactoe`.`player` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tictactoe`.`game_setup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`game_setup` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`game_setup` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `player1_char` CHAR NOT NULL DEFAULT 'X',
                                                        `player2_char` CHAR NOT NULL DEFAULT 'O',
                                                        `empty_char` CHAR NOT NULL DEFAULT '_',
                                                        `board_rows` BIGINT NOT NULL DEFAULT 3,
                                                        `board_columns` BIGINT NOT NULL DEFAULT 3,
                                                        PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tictactoe`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`game` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`game` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `player1` INT NOT NULL,
                                                  `player2` INT NOT NULL DEFAULT 0,
                                                  `game_setup_id` INT NOT NULL DEFAULT 0,
                                                  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  `game_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - not done (false)\n1 - done (true)',
                                                  PRIMARY KEY (`id`),
                                                  CONSTRAINT `fk_player1`
                                                      FOREIGN KEY (`player1`)
                                                          REFERENCES `tictactoe`.`player` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_player2`
                                                      FOREIGN KEY (`player2`)
                                                          REFERENCES `tictactoe`.`player` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_game_game_setup1`
                                                      FOREIGN KEY (`game_setup_id`)
                                                          REFERENCES `tictactoe`.`game_setup` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_player1_idx` ON `tictactoe`.`game` (`player1` ASC) INVISIBLE;

CREATE INDEX `fk_player2_idx` ON `tictactoe`.`game` (`player2` ASC) VISIBLE;

CREATE UNIQUE INDEX `player1_UNIQUE` ON `tictactoe`.`game` (`player1` ASC) VISIBLE;

CREATE INDEX `fk_game_game_setup1_idx` ON `tictactoe`.`game` (`game_setup_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tictactoe`.`move`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tictactoe`.`move` ;

CREATE TABLE IF NOT EXISTS `tictactoe`.`move` (
                                                  `id` INT NOT NULL,
                                                  `game_id` INT NOT NULL,
                                                  `player_id` INT NOT NULL DEFAULT 0,
                                                  `board_row` BIGINT NOT NULL DEFAULT 3,
                                                  `board_column` BIGINT NOT NULL DEFAULT 3,
                                                  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  PRIMARY KEY (`id`),
                                                  CONSTRAINT `fk_move_game1`
                                                      FOREIGN KEY (`game_id`)
                                                          REFERENCES `tictactoe`.`game` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_move_player1`
                                                      FOREIGN KEY (`player_id`)
                                                          REFERENCES `tictactoe`.`player` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_move_game1_idx` ON `tictactoe`.`move` (`game_id` ASC) VISIBLE;

CREATE INDEX `fk_move_player1_idx` ON `tictactoe`.`move` (`player_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `created_UNIQUE` ON `tictactoe`.`move` (`created` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tictactoe`.`player`
-- -----------------------------------------------------
START TRANSACTION;
USE `tictactoe`;
INSERT INTO `tictactoe`.`player` (`id`, `username`, `email`, `password`, `create_time`, `is_bot`) VALUES (0, 'kayo', 'kayo@playvalorant.com', '111111111', CURRENT_TIMESTAMP, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tictactoe`.`game_setup`
-- -----------------------------------------------------
START TRANSACTION;
USE `tictactoe`;
INSERT INTO `tictactoe`.`game_setup` (`id`, `player1_char`, `player2_char`, `empty_char`, `board_rows`, `board_columns`) VALUES (0, 'X', 'O', '_', 3, 3);

COMMIT;

